### ISSUE TITLE
Rename `maven-license-plugin` to `license-maven-plugin`

### ISSUE THREAD

**Issue by basil** [jenkinsci/license-maven-plugin#20]
Our Maven build contains the following warning:

> Artifact IDs of the format `maven-___-plugin` are reserved for plugins in the group ID `org.apache.maven.plugins`. Please change your artifact ID to the format `___-maven-plugin`. In the future this error will break the build.

[This notice](https://maven.apache.org/guides/plugin/guide-java-plugin-development.html#Important_Notice.3A_Plugin_Naming_Convention_and_Apache_Maven_Trademark) elaborates further:

> Calling it `maven-<yourplugin>-plugin` (note "Maven" is at the beginning of the plugin name) is **strongly discouraged** since it's a **reserved naming pattern for official Apache Maven plugins maintained by the Apache Maven team** with group ID `org.apache.maven.plugins`. Using this naming pattern is an infringement of the Apache Maven Trademark.

Renaming this plugin is trivial, but the real work in this task is adapting all consumers to the new name.

---

Reference: https://maven.apache.org/guides/plugin/guide-java-plugin-development.html

**Comment by jglick** [comment]
Perhaps merge with @NotMyFault’s proposal in https://github.com/jenkinsci/maven-license-plugin/pull/15#issuecomment-1620469798

> We _could_ cease publishing to the central repository and publish releases to repo.jenkins-ci.org.

and change the `groupId` while we are at it.

**Comment by timja** [comment]
Not too many usages:
https://github.com/search?q=org%3Ajenkinsci+%3CartifactId%3Emaven-license-plugin%3C%2FartifactId%3E+language%3A%22Maven+POM%22&type=code&l=Maven+POM&p=1

**Comment by basil** [comment]
> Fixed by #24 IIUC?

Partially. From the issue description:

> Renaming this plugin is trivial, but the real work in this task is adapting all consumers to the new name.

**Comment by basil** [comment]
Most of the affected plugins are dead, but at least two appear to be still maintained:

```
name                     popularity
-----------------------  ----------
jacoco                   22315     
gatling                  3405      
ldapemail                2303      
maven-release-cascade    677       
htmlresource             598       
BlazeMeterJenkinsPlugin  258       
associated-files         72        
plasticscm-mergebot      63        
TwilioNotifier           61        
```

Reopening until pull requests are filed to adapt JaCoCo and Gatling to this breaking change.

**Comment by jglick** [comment]
Filed https://github.com/jenkinsci/jacoco-plugin/pull/249. https://github.com/jenkinsci/gatling-plugin/blob/2a063c57ec094cba0521122bb036761e48a9ebe1/pom.xml#L117-L118 is unrelated I suppose.

**Comment by jglick** [comment]
Then I see https://github.com/jenkinsci/plugin-pom/pull/801 + https://github.com/jenkinsci/jenkins/pull/8231 + https://github.com/jenkinsci/pom/pull/460 which I suppose covers the normal stuff?

**Comment by basil** [comment]
Yeah, I think we have covered enough of the ecosystem to be able to declare success. The rest of the plugin references do not seem worth spending any time on.

**Comment by batmat** [comment]
I had in mind to ask this question when the move was initiated even before the rename. I guess this question is even more valid now :).

WDYT https://github.com/jenkinsci/license-maven-plugin/issues/33?
